In [ ]:
##Programming lab-17
##202311023 20/09/2023 

In [1]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


In [3]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [5]:
#np array joining
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2),axis=1)
arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [6]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [7]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1,arr2))
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.dstack((arr1,arr2))
arr


array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [11]:
arr = np.array([1,2,3,4,5,6])
new = np.array_split(arr,3)
print(new)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [29]:
# array slicing
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[:5])
print(arr[-3:-1])
print(arr[1:5:2])

[2 3 4 5]
[1 2 3 4 5]
[5 6]
[2 4]


In [31]:
#2d Array slicing
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr.dtype)

[7 8 9]
int32


In [32]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] =42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [33]:
x = arr.view()
arr[0] =42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [35]:
# shape
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr.shape)

(3, 3)


In [37]:
# reshape arr
arr = np.array([1,2,3,4,5,6,7,8,9])
new = arr.reshape(3,3)
print(arr)
print(new)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
#flateening

arr = np.array([1,2,3,4,5,6,7,8,9])
new = arr.reshape(3,3)
print(new)
new = arr.reshape(-1)
print(new)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [39]:
# join arrays

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]
