In [ ]:
##Programming lab-16
##202311023 13/09/2023 

In [7]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
list = [1,2,3,4]
print(type(list))

<class 'list'>


In [9]:
#np array using tupple
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [11]:
#Access Array Elements
print(arr[0])
print(arr[0] + arr[2])

1
4


In [17]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

print(arr[1,3])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
9


In [22]:
arr = np.array([[[1,2,3],[4,5,6,]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[1,0,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
8


In [23]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-1])

10


In [29]:
# array slicing
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[:5])
print(arr[-3:-1])
print(arr[1:5:2])

[2 3 4 5]
[1 2 3 4 5]
[5 6]
[2 4]


In [31]:
#2d Array slicing
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr.dtype)

[7 8 9]
int32


In [32]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] =42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [33]:
x = arr.view()
arr[0] =42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [35]:
# shape
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr.shape)

(3, 3)


In [37]:
# reshape arr
arr = np.array([1,2,3,4,5,6,7,8,9])
new = arr.reshape(3,3)
print(arr)
print(new)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
#flateening

arr = np.array([1,2,3,4,5,6,7,8,9])
new = arr.reshape(3,3)
print(new)
new = arr.reshape(-1)
print(new)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [39]:
# join arrays

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]
